version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    platform: linux/amd64 # важливо для M1/M2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=#2Pencil
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
